### ISSUE TITLE
verify in real time

### ISSUE THREAD

**Issue by lukasprelovsky** [hlashbrooke/WooCommerce-Email-Validation#3]
Good day I wish, I want to ask you do not plan to add the function verification email in real time. For example as a demonstration here: http://email-checker.net/check

**Comment by lukasprelovsky** [comment]
?

**Comment by hlashbrooke** [comment]
By "real time" do you mean checking to see if the email address actually exists? If that's the case then no - I will not be adding that feature for two main reasons:
- Depending on your server it can be very slow and it could have a hugely negative effect on your checkout conversion rates.
- If your server is slow then the request can easily time out, which would result in a lot of false negatives.

Ultimately, if people want to give a false email address then they will and there's no point in preventing them from doing so - asking them to verify their email address by typing it in twice is enough as that will make sure they type what they intend to type.

**Comment by lukasprelovsky** [comment]
Hello, the function is very important. On woocoommerce sent us customers Orders and requests evils email although it 2x writes. It's not enough. It would like to verification in real time how the example here http://email-checker.net/check

**Comment by hlashbrooke** [comment]
I understand that you want that, but I'm not going to add that function to the extension for the reasons that I mentioned above. I even worked on this feature a little while ago before deciding it would not be possible for those very reasons.
