### ISSUE TITLE
Validation breaks in woocommerce 3.0

### ISSUE THREAD

**Issue by NGiacopuzzi** [hlashbrooke/WooCommerce-Email-Validation#6]
Validation now always returns an error in woocommerce 3.0

**Comment by gwegner** [comment]
Same problem here. I had to deactivate the plugin for now.
Hoping for a quick fix!

**Comment by hlashbrooke** [comment]
This is fixed in v2.1 if the plugin, which I will release today :)

Thanks @ablears!
